# Generated by Django 5.2.8 on 2025-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_doctorrequest_patient_remove_offer_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
