# Generated by Django 5.2.8 on 2025-12-31 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='afya_plus_subscription', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled')], default='INACTIVE', max_length=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='The date the current paid-for period ends.', null=True)),
                ('consecutive_payment_failures', models.PositiveIntegerField(default=0, help_text='Tracks failed weekly payments for the grace period.')),
                ('africastalking_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
